{
  "openapi": "3.0.1",
  "info": {
    "title": "Consultorio API",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "Auth"
    },
    {
      "name": "ADMIN"
    },
    {
      "name": "ADMIN/Health Insurances"
    },
    {
      "name": "ADMIN/Patients Control"
    },
    {
      "name": "ADMIN/Treatments"
    },
    {
      "name": "ADMIN/Medical History"
    },
    {
      "name": "ADMIN/Dental Chart"
    },
    {
      "name": "Docs Area"
    },
    {
      "name": "Admin & Doc"
    },
    {
      "name": "Admin & Doc/Dental Charts"
    },
    {
      "name": "Admin & Doc/Medical History"
    },
    {
      "name": "Patients"
    },
    {
      "name": "Patients/Medical History"
    },
    {
      "name": "Patients/Appointments"
    },
    {
      "name": "Patients/Auth"
    }
  ],
  "paths": {
    "/api/auth/login": {
      "post": {
        "summary": "Login ",
        "deprecated": false,
        "description": "",
        "tags": [
          "Auth"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "email": "admin@gmail.com",
                "password": "admin123",
                "type": "string"
              },
              "example": {
                "email": "admin@gmail.com",
                "password": "admin123"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/auth/logout": {
      "post": {
        "summary": "Logout",
        "deprecated": false,
        "description": "",
        "tags": [
          "Auth"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU1OTE4NTIsImV4cCI6MTc0NTc2NDY1MiwibmJmIjoxNzQ1NTkxODUyLCJqdGkiOiJaY1djMDBZaWhoM3R5MFFiIiwic3ViIjoiMjkiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.-U3aORkLK7fDkyxuUO7qj1PsAsKdfYIsiEVnzT-jQS4",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": ""
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/auth/password-action": {
      "post": {
        "summary": "Reset Password",
        "deprecated": false,
        "description": "",
        "tags": [
          "Auth"
        ],
        "parameters": [
          {
            "name": "?",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "email": "fabi@gmail.com",
                "token": "f92ca9956cb20f6d085202c7808b285f989e0a1d949352276f233a362c847967",
                "password": "fabiana123",
                "password_confirmation": "fabiana123"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/usuario/1": {
      "put": {
        "summary": "Edit User Admin/Doc",
        "deprecated": false,
        "description": "",
        "tags": [
          "Auth"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2MjU5MTYsImV4cCI6MTc0NTc5ODcxNiwibmJmIjoxNzQ1NjI1OTE2LCJqdGkiOiJGS0Z6UFBVWVlhaWNQek1pIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Zh2d4X-Ji7B1S2q5RPjxdVEjxjx29J3XobkXBU3ymzs",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "user": "admin"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/auth/profile": {
      "post": {
        "summary": "View Profile",
        "deprecated": false,
        "description": "",
        "tags": [
          "Auth"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2ODEwNDgsImV4cCI6MTc0NTg1Mzg0OCwibmJmIjoxNzQ1NjgxMDQ4LCJqdGkiOiJjbWJZN3REaWY2bWwxYThjIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.0fOtms7YwwONywLkekNdsg9krQfONrQaw3pTW1HeFGc",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/obras_sociales": {
      "get": {
        "summary": "Get",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Health Insurances"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU1OTQxODAsImV4cCI6MTc0NTc2Njk4MCwibmJmIjoxNzQ1NTk0MTgwLCJqdGkiOiIwTkM5YnhKVFlOQndEYzJPIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.K1IuF4r63DwjucHxPrqFswGB7Z85H1kd5Fhp65fbdjI",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "post": {
        "summary": "Create",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Health Insurances"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU1OTQxODAsImV4cCI6MTc0NTc2Njk4MCwibmJmIjoxNzQ1NTk0MTgwLCJqdGkiOiIwTkM5YnhKVFlOQndEYzJPIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.K1IuF4r63DwjucHxPrqFswGB7Z85H1kd5Fhp65fbdjI",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "obra_social": "UNAM"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/obras_sociales/6": {
      "delete": {
        "summary": "Delete",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Health Insurances"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2MjI4NDYsImV4cCI6MTc0NTc5NTY0NiwibmJmIjoxNzQ1NjIyODQ2LCJqdGkiOiIxamwyWXdNcU55Sld5ZDA5Iiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.uyvjyKNCsljEp_2nruhoZoVWNr-LZmFzIw76cw7wcJE",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/usuarios/obra_social/search/IPS": {
      "get": {
        "summary": "Get ID",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Health Insurances"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2MjI4NDYsImV4cCI6MTc0NTc5NTY0NiwibmJmIjoxNzQ1NjIyODQ2LCJqdGkiOiIxamwyWXdNcU55Sld5ZDA5Iiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.uyvjyKNCsljEp_2nruhoZoVWNr-LZmFzIw76cw7wcJE",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/pacientes": {
      "get": {
        "summary": "Get",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Patients Control"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2MjM2NTAsImV4cCI6MTc0NTc5NjQ1MCwibmJmIjoxNzQ1NjIzNjUwLCJqdGkiOiJBMzFDUjZmR1UxUGwxS2xRIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.J1zGGyteU1pkk4z9QDp-Gf2Zm_mkaPWWB6SfCA5YQ9k",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/usuarios/nombre/Fabiana": {
      "get": {
        "summary": "Get Patients For Name",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Patients Control"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2MjU5MTYsImV4cCI6MTc0NTc5ODcxNiwibmJmIjoxNzQ1NjI1OTE2LCJqdGkiOiJGS0Z6UFBVWVlhaWNQek1pIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Zh2d4X-Ji7B1S2q5RPjxdVEjxjx29J3XobkXBU3ymzs",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/usuarios/apellido/Bordon": {
      "get": {
        "summary": "Get Patients For Last Name",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Patients Control"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2MjU5MTYsImV4cCI6MTc0NTc5ODcxNiwibmJmIjoxNzQ1NjI1OTE2LCJqdGkiOiJGS0Z6UFBVWVlhaWNQek1pIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Zh2d4X-Ji7B1S2q5RPjxdVEjxjx29J3XobkXBU3ymzs",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/usuarios/busqueda/Lautaro/Bordon": {
      "get": {
        "summary": "Get Patients For Name & Last Name",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Patients Control"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2MjU5MTYsImV4cCI6MTc0NTc5ODcxNiwibmJmIjoxNzQ1NjI1OTE2LCJqdGkiOiJGS0Z6UFBVWVlhaWNQek1pIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Zh2d4X-Ji7B1S2q5RPjxdVEjxjx29J3XobkXBU3ymzs",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/usuarios/obras_sociales/OSDE": {
      "get": {
        "summary": "Get Patients For Obra Social",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Patients Control"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2MjU5MTYsImV4cCI6MTc0NTc5ODcxNiwibmJmIjoxNzQ1NjI1OTE2LCJqdGkiOiJGS0Z6UFBVWVlhaWNQek1pIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Zh2d4X-Ji7B1S2q5RPjxdVEjxjx29J3XobkXBU3ymzs",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/tratamientos/create": {
      "post": {
        "summary": "Create",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Treatments"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2ODAxMjMsImV4cCI6MTc0NTg1MjkyMywibmJmIjoxNzQ1NjgwMTIzLCJqdGkiOiJudElqaldLVVp0cWN0VlNwIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.a_myhzJ3vqc_X5OyuKQw1RuVKrKsWaKt4xRKnmfk51M",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "nombre": "Conducto en premolar"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/tratamientos/list": {
      "get": {
        "summary": "Get",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Treatments"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2ODAxMjMsImV4cCI6MTc0NTg1MjkyMywibmJmIjoxNzQ1NjgwMTIzLCJqdGkiOiJudElqaldLVVp0cWN0VlNwIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.a_myhzJ3vqc_X5OyuKQw1RuVKrKsWaKt4xRKnmfk51M",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": ""
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "Delete",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Treatments"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2ODAxMjMsImV4cCI6MTc0NTg1MjkyMywibmJmIjoxNzQ1NjgwMTIzLCJqdGkiOiJudElqaldLVVp0cWN0VlNwIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.a_myhzJ3vqc_X5OyuKQw1RuVKrKsWaKt4xRKnmfk51M",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": ""
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/tratamientos/search/conducto": {
      "get": {
        "summary": "Get For Name",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Treatments"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDU2ODAxMjMsImV4cCI6MTc0NTg1MjkyMywibmJmIjoxNzQ1NjgwMTIzLCJqdGkiOiJudElqaldLVVp0cWN0VlNwIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.a_myhzJ3vqc_X5OyuKQw1RuVKrKsWaKt4xRKnmfk51M",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": ""
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/legajo/create": {
      "post": {
        "summary": "Create",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Medical History"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY0NDg3NTUsImV4cCI6MTc0NjYyMTU1NSwibmJmIjoxNzQ2NDQ4NzU1LCJqdGkiOiJ3ajhmSFhwNnJmSjVIRXBsIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.amWY4-wad-4RR9g6eyG5meq6mWX1c-pJF03WVraSG5s",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "paciente_id": 26,
                "descripcion": "muela del juicio a extraer lado izquierdo",
                "user_id": 2,
                "tratamiento_id": 9,
                "fecha": "2025-05-05"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/profesional/list": {
      "get": {
        "summary": "Get Dentists",
        "deprecated": false,
        "description": "",
        "tags": [
          "Patients/Appointments"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "first_name": {
                        "type": "string"
                      },
                      "last_name": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "first_name",
                      "last_name"
                    ]
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/odontograma/create": {
      "post": {
        "summary": "Create",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Dental Chart"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY0NTE1ODUsImV4cCI6MTc0NjYyNDM4NSwibmJmIjoxNzQ2NDUxNTg1LCJqdGkiOiJRQk83ZE9GSEltUGJnY250Iiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.7ezyRmWHKwA7VHxxtYRGfa3WzcrlHZctCB_T_xzaEpw",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "paciente_id": 20,
                "pieza_id": [
                  6,
                  9
                ],
                "tratamiento_id": 10,
                "anomalia_color_id": 2,
                "cara_odontograma_id": 5,
                "diagnostico": "probando odonto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/odontograma/update/7": {
      "put": {
        "summary": "Update",
        "deprecated": false,
        "description": "",
        "tags": [
          "ADMIN/Dental Chart"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY2MTk5MDksImV4cCI6MTc0Njc5MjcwOSwibmJmIjoxNzQ2NjE5OTA5LCJqdGkiOiI0WjFHdWg0WGowRUtYWjRsIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.RdLreHzd_uZ5_oR_r1uI6bEMn6xSTZxr0eBcTFby3P0",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "paciente_id": 20,
                "pieza_id": [
                  6,
                  10
                ],
                "tratamiento_id": 10,
                "anomalia_color_id": 1,
                "cara_odontograma_id": 5,
                "diagnostico": "probando odonto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/doc/pacientes/turnos/2": {
      "get": {
        "summary": "Get Today Patients",
        "deprecated": false,
        "description": "",
        "tags": [
          "Docs Area"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDYwMjUzMzUsImV4cCI6MTc0NjE5ODEzNSwibmJmIjoxNzQ2MDI1MzM1LCJqdGkiOiJ5VmxYcnBKNHEybHZPUGs4Iiwic3ViIjoiMiIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.hLyj0pRROmlBCLZUBtL8UznCv5sxQavM1G2ml3Dqhqk",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/pacientes/filtrar-turnos-dia/20250505": {
      "get": {
        "summary": "Get Appointments By Date",
        "deprecated": false,
        "description": "",
        "tags": [
          "Docs Area"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY3MTA5MjIsImV4cCI6MTc0Njg4MzcyMiwibmJmIjoxNzQ2NzEwOTIyLCJqdGkiOiJBeGRPNFZwTTBORlZSdVJkIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.xFq-tj2qUYSPv8BA2VsasH5pxNnSD7BXIZyywK3RIjs",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/pacientes/filtrar-turnos-mes/5": {
      "get": {
        "summary": "Get Appointmenst By Month",
        "deprecated": false,
        "description": "",
        "tags": [
          "Docs Area"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/piezas/select": {
      "get": {
        "summary": "Get Dental Pieces",
        "deprecated": false,
        "description": "",
        "tags": [
          "Admin & Doc/Dental Charts"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY2MTk5MDksImV4cCI6MTc0Njc5MjcwOSwibmJmIjoxNzQ2NjE5OTA5LCJqdGkiOiI0WjFHdWg0WGowRUtYWjRsIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.RdLreHzd_uZ5_oR_r1uI6bEMn6xSTZxr0eBcTFby3P0",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/caras_dentales/select": {
      "get": {
        "summary": "Get Dental Surfaces",
        "deprecated": false,
        "description": "",
        "tags": [
          "Admin & Doc/Dental Charts"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY0NTE1ODUsImV4cCI6MTc0NjYyNDM4NSwibmJmIjoxNzQ2NDUxNTg1LCJqdGkiOiJRQk83ZE9GSEltUGJnY250Iiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.7ezyRmWHKwA7VHxxtYRGfa3WzcrlHZctCB_T_xzaEpw",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/colores_anomalias/select": {
      "get": {
        "summary": "Get Anomaly Colors",
        "deprecated": false,
        "description": "",
        "tags": [
          "Admin & Doc/Dental Charts"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY0NTE1ODUsImV4cCI6MTc0NjYyNDM4NSwibmJmIjoxNzQ2NDUxNTg1LCJqdGkiOiJRQk83ZE9GSEltUGJnY250Iiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.7ezyRmWHKwA7VHxxtYRGfa3WzcrlHZctCB_T_xzaEpw",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/odontograma/list": {
      "get": {
        "summary": "Get All Dental Charts",
        "deprecated": false,
        "description": "",
        "tags": [
          "Admin & Doc/Dental Charts"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY2MTgzNzcsImV4cCI6MTc0Njc5MTE3NywibmJmIjoxNzQ2NjE4Mzc3LCJqdGkiOiIwRHdZT3Y0ckRSR2JPdk1wIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.-OF0c0IC426wBAQM5bQcUUbpWuVTdLxW6fWZZ1ReO_o",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/legajo/list": {
      "get": {
        "summary": "Get All Medical History",
        "deprecated": false,
        "description": "",
        "tags": [
          "Admin & Doc/Medical History"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY0NDg3NTUsImV4cCI6MTc0NjYyMTU1NSwibmJmIjoxNzQ2NDQ4NzU1LCJqdGkiOiJ3ajhmSFhwNnJmSjVIRXBsIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.amWY4-wad-4RR9g6eyG5meq6mWX1c-pJF03WVraSG5s",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/admin/legajo/last_legajo/26": {
      "get": {
        "summary": "Show",
        "deprecated": false,
        "description": "",
        "tags": [
          "Patients/Medical History"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/paciente/turnos/create": {
      "post": {
        "summary": "Create",
        "deprecated": false,
        "description": "",
        "tags": [
          "Patients/Appointments"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDYwMjMwMTQsImV4cCI6MTc0NjE5NTgxNCwibmJmIjoxNzQ2MDIzMDE0LCJqdGkiOiJ2ZlJaYXpoNUYxejNiTXROIiwic3ViIjoiMjkiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.yQxo14YfjALHhGK-AsOnG0dbQd7F8NWJagN4XPhfB5A",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "user_id": 2,
                "motivo_consulta": "mucho dolor",
                "fecha": "2025-05-14",
                "hora": "09:00",
                "paciente_id": 26
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/paciente/turnos/show/3": {
      "get": {
        "summary": "Show",
        "deprecated": false,
        "description": "",
        "tags": [
          "Patients/Appointments"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDYwMjMwMTQsImV4cCI6MTc0NjE5NTgxNCwibmJmIjoxNzQ2MDIzMDE0LCJqdGkiOiJ2ZlJaYXpoNUYxejNiTXROIiwic3ViIjoiMjkiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.yQxo14YfjALHhGK-AsOnG0dbQd7F8NWJagN4XPhfB5A",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": ""
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/paciente/turnos/cancelar/26": {
      "get": {
        "summary": "Get Specialties",
        "deprecated": false,
        "description": "",
        "tags": [
          "Patients/Appointments"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDYwMjMwMTQsImV4cCI6MTc0NjE5NTgxNCwibmJmIjoxNzQ2MDIzMDE0LCJqdGkiOiJ2ZlJaYXpoNUYxejNiTXROIiwic3ViIjoiMjkiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.yQxo14YfjALHhGK-AsOnG0dbQd7F8NWJagN4XPhfB5A",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": ""
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/fechas/2025-05-10": {
      "get": {
        "summary": "Get Slots",
        "deprecated": false,
        "description": "",
        "tags": [
          "Patients/Appointments"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY2MTk5MDksImV4cCI6MTc0Njc5MjcwOSwibmJmIjoxNzQ2NjE5OTA5LCJqdGkiOiI0WjFHdWg0WGowRUtYWjRsIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.RdLreHzd_uZ5_oR_r1uI6bEMn6xSTZxr0eBcTFby3P0",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/auth/register": {
      "post": {
        "summary": "Register",
        "deprecated": false,
        "description": "",
        "tags": [
          "Patients/Auth"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}